project_id = "qzwxisdfwswsrbzvpzlo"

[functions.generate-pep-pdf]
verify_jwt = false

[functions.get-app-version]
verify_jwt = false

[functions.import-employees]
verify_jwt = false

[functions.sync-auth-users]
verify_jwt = false