project_id = "qzwxisdfwswsrbzvpzlo"

[functions.employee-auth]
verify_jwt = false

[functions.generate-pep-pdf]
verify_jwt = false

[functions.get-app-version]
verify_jwt = false

[functions.import-employees]
verify_jwt = false

[functions.submit-evaluation]
verify_jwt = false
